- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Wait 300 seconds for port 8000 to become open on the host, don't start checking for 10 seconds
      wait_for:
        port: 65511
        delay: 10

